server:
  port: 7979

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  forceOriginalQueryStringEncoding: true
  routes:
    uac-route:
      path: /uac/**
      sensitiveHeaders:
#      strip-prefix: false
      service-id: saascloud-provider-uac
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
  add-proxy-headers: true
  add-host-header: true

#security:
#  oauth2:
#    client:
#      clientId: saascloud-client-gateway
#      clientSecret: saascloudClientSecret
#      access-token-uri: http://saascloud-gateway:7979/uac/oauth/token
#      user-authorization-uri: http://saascloud-gateway:7979/uac/oauth/authorize
#    resource:
#      user-info-uri: http://saascloud-gateway:7979/uac/user
#      prefer-token-info: false
#      jwt:
#        key-uri: http://saascloud-provider-uac:8001/oauth/token_key

proxy:
  auth:
    routes:
      uac-route: oauth2
      mdc-route: oauth2

paascloud:
  enableSqlLogInterceptor: false
# swagger butler配置
swagger.butler:
  api-docs-path: v2/api-docs
  swagger-version: 1.0
  auto-generate-from-zuul-routes: true
# 指定要生成的范围
  generate-routes: omc-route,mdc-route,opc-route,tpc-route,uac-route
# 忽略某些路由生成
#  ignore-routes: